version: '3.1'

services:
  db:
    image: postgres:15.3-alpine3.18
    ports:
      - "127.0.0.1:5432:5432"
    restart: always
    environment:
      POSTGRES_DB: pattern_finder
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: zxc
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql